config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :definitions do
    member do
      get 'sentence_case'
      get 'titlecase'
    end
  end
  resources :dictionaries do
    member do
      get 'merge_duplicates'
    end
  end
  resources :acronyms
  resources :documents

  get 'users#sign_up' => 'document#new'

  root 'documents#new'

  get 'about' => 'static#about'
end

app/models/definition.rb
# == Schema Information
#
# Table name: definitions
#
#  id            :integer          not null, primary key
#  dictionary_id :integer
#  initialism    :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  meaning       :string
#


class Definition < ActiveRecord::Base
  belongs_to :dictionary

  validates :initialism, length: {minimum: 2}
  validates :meaning, length: {minimum: 2}
  validates :dictionary, presence: true

  # Top level sort: auto-mergeables, conflicts, uniques
  # Second: initialism
  # Third: meaning
  def <=>(other)
    # Bump one to the surface if it is conflicted and the other isn't
    #return -1 if (conflicted? and !other.conflicted?)
    #return  1 if (!conflicted? and other.conflicted?)
    comparison = (sort_level <=> other.sort_level)
    return comparison unless comparison == 0
    # Next sort by initialism, then meaning
    comparison = (initialism.downcase <=> other.initialism.downcase)
    return comparison unless comparison == 0
    meaning.downcase <=> other.meaning.downcase
  end

  def to_s
    initialism
  end
  def conflicted? # true if this dictionary has another instance of this initialism (regardless of whether the meanings are the same)
    #true
    dictionary.count_definitions(initialism) > 1
  end
  def duplicate? # true if there is another Definition with same initialism, same meaning
    dictionary.definitions.each do |definition|
      next if id == definition.id # don't compare with self
      return true if identical_to?(definition)
    end
    false
  end

  def css_id
    if conflicted?
      if duplicate?
        'duplicate'
      else
        'conflicted'
      end
    else
      'unique'
    end
  end
  def sort_level
    return 0 if duplicate?
    return 1 if conflicted?
    return 2
  end

  def sentence_case!
    self.meaning = self.meaning.humanize
    self.save!
  end

  def titlecase!
    self.meaning = self.meaning.titlecase
    self.save!
  end

  private
  def identical_to?(other)
    raise "Comparison with self makes no sense" if id == other.id
    return ((initialism == other.initialism) and (meaning == other.meaning))
  end
end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_action :set_definition, only: [:show, :edit, :update, :destroy, :sentence_case, 
    :titlecase]
  before_action :authenticate_user!

  # GET /definitions
  # GET /definitions.json
  def index
    @definitions = Definition.all
  end

  # GET /definitions/1
  # GET /definitions/1.json
  def show
  end

  # GET /definitions/new
  def new
    set_dictionary
    @definition = Definition.new
  end

  # GET /definitions/1/edit
  def edit
  end

  # GET /definitions/1/sentence_case
  def sentence_case
    @definition.sentence_case!
    redirect_to @definition.dictionary || @definition
  end

  # GET/definitions/1/title_case
  def titlecase
    @definition.titlecase!
    redirect_to @definition.dictionary || @definition
  end

  # POST /definitions
  # POST /definitions.json
  def create
    @definition = Definition.new(definition_params)

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @definition.dictionary, notice: 'Definition was successfully created.' }
        format.json { render :show, status: :created, location: @definition }
      else
        format.html { render :new }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /definitions/1
  # PATCH/PUT /definitions/1.json
  def update
    respond_to do |format|
      if @definition.update(definition_params)
        format.html { redirect_to @definition.dictionary || @definition, notice: 'Definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @definition }
      else
        format.html { render :edit }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /definitions/1
  # DELETE /definitions/1.json
  def destroy
    dictionary = @definition.dictionary
    @definition.destroy
    respond_to do |format|
      format.html { redirect_to dictionary_url(dictionary.id), notice: 'Definition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_definition
      @definition = Definition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def definition_params
      params.require(:definition).permit(:dictionary_id, :initialism, :meaning)
    end

    def set_dictionary
      @dictionary = Dictionary.find(params[:dictionary_id])
    end
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/views/definitions/_definition.html.haml
%tr{ id: definition.css_id }
  %td= definition.dictionary
  %td= definition.initialism
  %td= definition.meaning
  %td= link_to 'Sentence case', sentence_case_definition_path(definition)
  %td= link_to 'Title case', titlecase_definition_path(definition)
  %td= link_to 'Show', definition
  %td= link_to 'Edit', edit_definition_path(definition)
  %td= link_to 'Destroy', definition, method: :delete #, data: { confirm: 'Are you sure?' }

app/views/definitions/_form.html.haml
- @dictionary ||= @definition.dictionary
= form_for(@definition) do |f|
  - if @definition.errors.any?
    #error_explanation
      %h2
        = pluralize(@definition.errors.count, "error")
        prohibited this definition from being saved:
      %ul
        - @definition.errors.full_messages.each do |message|
          %li= message
  .field
    = f.hidden_field :dictionary_id, value: @dictionary.id
  .field
    = f.label :initialism
    %br/
    = f.text_field :initialism, size: 50
  .field
    = f.label :meaning
    %br/
    = f.text_field :meaning, size: 50
  .actions
    = f.submit

app/views/definitions/_list.html.haml
%table
  %thead
    %tr
      %th Dictionary
      %th Initialism
      %th Meaning
      %th{:colspan => "3"}
  %tbody
    - @definitions.each do |definition|
      %tr
        %td= definition.dictionary
        %td= definition.initialism
        %td= definition.meaning
        %td= link_to 'Show', definition
        %td= link_to 'Edit', edit_definition_path(definition)
        %td= link_to 'Destroy', definition, method: :delete, data: { confirm: 'Are you sure?' }

app/views/definitions/edit.html.haml
%h1 Editing Definition
= render 'form'
= link_to 'Show', @definition
|
= link_to 'Back', definitions_path

app/views/definitions/index.html.haml
%h1 Listing Definitions
%table
  %thead
    %tr
      %th Dictionary
      %th Initialism
      %th Meaning
      %th{:colspan => "3"}
  %tbody
    - @definitions.order(:initialism).each do |definition|
      %tr
        %td= definition.dictionary
        %td= definition.initialism
        %td= definition.meaning
        %td= link_to 'Show', definition
        %td= link_to 'Edit', edit_definition_path(definition)
        %td= link_to 'Destroy', definition, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Definition', new_definition_path

app/views/definitions/new.html.haml
%h1 New Definition
= render 'form'
= link_to 'Back', definitions_path

app/views/definitions/show.html.haml
%p
  %strong Dictionary:
  = @definition.dictionary
%p
  %strong Initialism:
  = @definition.initialism
%p
  %strong Meaning:
  = @definition.meaning
= link_to 'Edit', edit_definition_path(@definition)
|
= link_to 'Back', dictionary_path(@definition.dictionary)