config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :definitions do
    member do
      get 'sentence_case'
      get 'titlecase'
    end
  end
  resources :dictionaries do
    member do
      get 'merge_duplicates'
    end
  end
  resources :acronyms
  resources :documents

  get 'users#sign_up' => 'document#new'

  root 'documents#new'

  get 'about' => 'static#about'
end

app/models/dictionary.rb
# == Schema Information
#
# Table name: dictionaries
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class Dictionary < ActiveRecord::Base
  has_many :definitions, -> { order(initialism: :desc) }
  has_many :documents
  # Don't use commas because of definitions like ACP: Africa, Caribbean and Pacific group of countries (and UNESCO)
  DELIMITER = /[\t\;]/

  #def after_create
  #  binding.pry
  #end

  def include?(initialism)
    definitions.to_a.include? initialism
  end
  def to_s
    name
  end

  def lookup(initialism)
    # Returns zero or one result
    definition = definitions.find_by initialism: initialism
    definition ? definition.meaning : nil
  end

  # quick_add is a pseudo-field in dictionaries
  # "Get" quick_add field -- i.e. what to put in the form's text_area (nothing)
  def quick_add; end
  
  def quick_add=(data)
    data.lines.collect {|l| l.strip }.each do |def_line|
      if def_line =~ DELIMITER
        initialism,meaning = def_line.split DELIMITER
        unless include? initialism
          definitions.push Definition.new( initialism: initialism.strip, meaning: meaning.strip )
        end
      end
    end
  end

  def merge_duplicates
    duplicate_count = 0
    # initialism => [ definition1, definition2, ... ]
    definitions.group_by(&:initialism).each_pair do |i,d|
      # i=initialism
      # d=[ definitions ]
      logger.info "Comparing definitions of #{i}"
      next if d.length == 1 # only one listing of this initialism
      d.group_by(&:meaning).each_pair do |m,e|
        # m: meaning
        # e: [ deftinitions ]
        logger.info "Dealing with duplicates of #{i} = #{m}"
        e.pop # keep the first definition using this meaning
        # if any remain, they're duplicates
        e.each do |duplicate|
          duplicate_count += 1
          duplicate.destroy
        end
      end
    end
    return duplicate_count
  end

  def count_definitions(initialism)
    definitions.group_by(&:initialism)[initialism].length
  end
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy, :merge_duplicates]
  before_action :authenticate_user!, except: [:show]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
    #add_definitions(dictionary_params)
  end

  # GET /dictionaries/1/edit
  def edit
    #add_definitions(dictionary_params)
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_real_params)
    @dictionary.save # we're in trouble if this blows up -- currently no validation
                     # of the name so it is less bad than the previous.
    @dictionary.update(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def merge_duplicates
    logger.info "Merging duplicates in #{@dictionary.name}..."
    #binding.pry
    respond_to do |format|
      if count = @dictionary.merge_duplicates
        count_s_were = count == 1 ? ' was' : 's were'
        format.html { redirect_to @dictionary, notice: "#{count} duplicate#{count_s_were} successfully merged." }
        #format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { redirect_to @dictionary, alert: 'Failed!' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
      params.require(:dictionary).permit(:name, :quick_add)
    end
    def dictionary_real_params
      params.require(:dictionary).permit(:name)
    end
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.html.haml
= form_for(@dictionary) do |f|
  - if @dictionary.errors.any?
    #error_explanation
      %h2
        = pluralize(@dictionary.errors.count, "error")
        prohibited this dictionary from being saved:
      %ul
        - @dictionary.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :quick_add, "Quickly upload many definitions (one per line, tab delimited)"
    %br/
    = f.text_area :quick_add, size: "60x25"
  .actions
    = f.submit

app/views/dictionaries/edit.html.haml
%h1 Editing Dictionary
= render 'form'
= link_to 'Show', @dictionary
|
= link_to 'Back', dictionaries_path

app/views/dictionaries/index.html.haml
%h1 Listing Dictionaries
%table{ width: '100%' }
  %thead
    %tr
      %th Name
      %th Length
      %th{colspan: '3'} Actions
  %tbody
    - @dictionaries.each do |dictionary|
      %tr
        %td= dictionary.name
        %td= dictionary.definitions.count
        %td= link_to 'Show', dictionary
        %td= link_to 'Edit', edit_dictionary_path(dictionary)
        %td= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Dictionary', new_dictionary_path

app/views/dictionaries/new.html.haml
%h1 New Dictionary
= render 'form'
= link_to 'Back', dictionaries_path

app/views/dictionaries/show.html.haml
%h1= "Dictionary: #{@dictionary.name}"
%p
  = link_to 'Quick add', edit_dictionary_path(@dictionary)
  |
  = link_to 'Individual add', new_definition_path({ dictionary_id: @dictionary.id }) #add_definition_dictionary_path(@dictionary)
  |
  = link_to 'Merge duplicates', merge_duplicates_dictionary_path(@dictionary)
  |
  = link_to 'Back to all dictionaries', dictionaries_path
%table{ width: '100%' }
  %thead
    %tr
      %th Dictionary
      %th Initialism
      %th Meaning
      %th{:colspan => "5"} Actions
  %tbody
    - @dictionary.definitions.sort.each do |definition|
      = render definition